<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="DbcontentGridView.aspx.cs" Inherits="DemoProject.DbcontentGridView" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        a{color: beige;          
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />    
    <asp:GridView runat="server" ID="carsGrid" ItemType="DemoProject.CarsTable" DataKeyNames="Id"
         SelectMethod="carsGrid_GetData" UpdateMethod="carsGrid_UpdateItem" DeleteMethod="carsGrid_DeleteItem"
         AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
         AutoGenerateColumns="true">         
    </asp:GridView>
    <asp:HyperLink NavigateUrl="~/AddCar.aspx" Text="Add New Car" runat="server" />
   
</asp:Content>
